eureka:
  client:
    register-with-eureka: false

server:
  port: 8081

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        discovery:
          locator:
            enabled: true
      mvc:
        routes:
          - id: students
            uri: http://localhost:8090
            predicates:
              - Path=/students/**
          - id: courses
            uri: http://localhost:9090
            predicates:
              - Path=/courses/**

